### ISSUE TITLE
TranzWarePaymentGatewayOrderRequest::setStrictSSL

### ISSUE THREAD

**Issue by m0bua** [Open-Payment-Solutions/TranzWarePaymentGatewayApi#3]
Fatal error: Declaration of OpenPaymentSolutions\TranzWarePaymentGateway\Requests\TranzWarePaymentGatewayOrderRequest::setStrictSSL($enable) must be compatible with OpenPaymentSolutions\TranzWarePaymentGateway\Requests\TranzWarePaymentGatewayRequestInterface::setStrictSSL($enable = true) in vendor/open-payment-solutions/tranzware-payment-gateway/src/requests/TranzWarePaymentGatewayOrderRequest.php on line 12

**Comment by num8er** [comment]
shame on me. :(

@m0b-ua  thank You very much for writing about issue

feel free to check 1.1.9 and inform if issue still exists.
