### ISSUE TITLE
CURLOPT_SSL_VERIFYHOST

### ISSUE THREAD

**Issue by m0bua** [Open-Payment-Solutions/TranzWarePaymentGatewayApi#4]
curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead
in vendor/open-payment-solutions/tranzware-payment-gateway/src/requests/TranzWarePaymentGatewayHTTPClient.php(77)

**Comment by Jonston** [comment]
> curl_setopt(): CURLOPT_SSL_VERIFYHOST no longer accepts the value 1, value 2 will be used instead
> in vendor/open-payment-solutions/tranzware-payment-gateway/src/requests/TranzWarePaymentGatewayHTTPClient.php(77)

I think we need to use Guzzle HTTP client instead raw curl queries.

**Comment by num8er** [comment]
@m0b-ua  @Jonston  You're awesome. 
Thank You very much for informing about issues.
Please check and make sure fixes are successful.
Cheers

**Comment by num8er** [comment]
Hoping to get some time to write tests to avoid such situations.
