### ISSUE TITLE
get_status.php 

### ISSUE THREAD

**Issue by gemsam50sabana** [Open-Payment-Solutions/TranzWarePaymentGatewayApi#5]
When run get_status.php file after run create.php file for create order - get_status.php file error like screenshot below
![er3](https://user-images.githubusercontent.com/111701457/185803744-025eb301-aaf3-4109-aaf4-6a5d00adae4b.jpg)
![er2](https://user-images.githubusercontent.com/111701457/185803748-7df898ce-9bcc-459b-b053-a8e71ccf2cd3.jpg)
![er1](https://user-images.githubusercontent.com/111701457/185803752-52bb0d13-1feb-4c15-a575-bfe79c7668fd.jpg)

**Comment by num8er** [comment]
@gemsam50sabana Hi, it's due to empty OrderID which expected to be provided in get_status.php through $_GET['ORDERID']
So I've added to throw exceptions to inform about that.

Thank You for opening issue.
